services:
  minicommerce.inventoryservice.api:
    image: ${DOCKER_REGISTRY-}minicommerceinventoryserviceapi
    build:
      context: .
      dockerfile: MiniCommerce.InventoryService.Api/Dockerfile
